version: '3.7'

services:
  minio2:
    restart: always
    image: 'bitnami/minio:latest'
    container_name: minio2
    hostname: minio2
    ports:
      - '16543:9000'  # Custom port mapping
      - '16544:9001'  # Custom console port mapping
    environment:
      - MINIO_ROOT_USER=newton
      - MINIO_ROOT_PASSWORD=4igb2gxP4p8KrzQ3YnHXtnBCMCbknKV8kU6bDq6RJ457TJE9es8JFKcJ56pLFCid8eFwbpVdQqP4m5396b7G5w2GdA
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=http://89.168.43.18:9000,http://158.178.203.52:16543
      - MINIO_SKIP_CLIENT=yes
    extra_hosts:
      - "minio1:89.168.43.18"  # Node 1
      - "minio2:158.178.203.52"  # Node 2
    volumes:
      - /opt/docker/minio/data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
