import subprocess
import time
from utils import *
import re

def remove_punctuation_and_whitespace(text):
    # Use regex to remove all non-alphabetic characters
    cleaned_text = re.sub(r'[^a-zA-Z]', '', text)
    return cleaned_text

emojis_dir = "emojis/images/"

def overlay_images_on_video(in_path, out_path, width, height, ass, emojis_list=None):
    """
    Overlays images on a video using ffmpeg.

    Args:
        in_path (str): Path to the input video.
        out_path (str): Path to save the output video.
        width (int): Width of the video.
        height (int): Height of the video.
        ass (str): Path to the ASS subtitle file.
        emojis_list (list, optional): List of tuples (IMAGE_WORKER_NAME, start_time, end_time)
            specifying images to overlay and their display times.

    Returns:
        None
    """
    emoji_size = height / 10
    y_offset = width / 100
    swidth = (width - emoji_size) / 2
    sheight = (height - emoji_size) / 2 - 3*y_offset

    filter_complex = ""

    if emojis_list is not None:
        # Prepare emoji input list for ffmpeg
        emojis_list = [(emojis_dir + image + ".png", start_time, end_time) for image, start_time, end_time in emojis_list]

        for idx, (IMAGE_WORKER_NAME, start_time, end_time) in enumerate(emojis_list):
            previous_video = f"[{idx}v]" if idx > 0 else "[0:v]"
            # Build overlay filter for each emoji image
            filter_complex += f"{previous_video}[{idx + 1}:v]overlay={swidth}:{sheight}:enable='between(t,{start_time},{end_time})'"
            if idx < len(emojis_list) - 1:
                filter_complex += f"[{idx + 1}v];"
            else:
                filter_complex += f"[last];[last]ass='{ass}'[out]"

        # Construct the complete ffmpeg command
        cmd = (
            f"ffmpeg -i {in_path} {' '.join(['-i ' + image for image, _, _ in emojis_list])} "
            f"-filter_complex \"{filter_complex}\" -map [out] -map 0:a -c:a copy {out_path} -y"
        )
    else:
        # If no emojis, use ASS subtitles directly with video overlay
        cmd = f"ffmpeg -i {in_path} -vf 'ass={ass}' -c:a copy -y {out_path}"

    # Execute the ffmpeg command
    tic = time.perf_counter()
    subprocess.run(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    toc = time.perf_counter()
    time_encoding = toc - tic

    # Measure and print execution time
    print(f"ffmpeg processing for video took: {time_encoding} seconds")
    return time_encoding

# Example usage:
# overlay_images_on_video('input.mp4', 'output.mp4', 1280, 720, 'subtitles.ass', emojis_list=[('emoji1', 5.0, 10.0), ('emoji2', 15.0, 20.0)])
# overlay_images_on_video('input.mp4', 'output.mp4', 1280, 720, 'subtitles.ass')


def fetch_similar_emojis(array):
    emojis_list = []
    current_iteration_found_emoji = False
    current_iteration_found_emoji_number = "0"
    for i in array:
        current_iteration_found_emoji = False
        current_iteration_found_emoji_number = "0"
        word_ref = i[2]
        for word in word_ref:
            for line in flatten_array:
                numero = line[0]
                for echo in line[1]:
                    word_clean = remove_punctuation_and_whitespace(word)
                    if (echo.lower() == word_clean):
                        current_iteration_found_emoji = True
                        current_iteration_found_emoji_number = numero
                        print("Found match for "+ echo + " corresding to emoji "+ numero)
        if current_iteration_found_emoji :                
            emojis_list.append([current_iteration_found_emoji_number,i[0],i[1]])
    print(str(len(emojis_list))+ " emojis have been found")
    return emojis_list

array = [
    ["1","😀","grinning face",""],
    ["2","😃","grinning face with big eyes",""],
    ["3","😄","grinning face with smiling eyes",""],
    ["4","😁","beaming face with smiling eyes",""],
    ["5","😆","grinning squinting face",""],
    ["6","😅","grinning face with sweat",""],
    ["7","🤣","rolling on the floor laughing",""],
    ["8","😂","face with tears of joy",""],
    ["9","🙂","slightly smiling face",""],
    ["10","🙃","upside-down face",""],
    ["11","😉","winking face",""],
    ["12","😊","smiling face with smiling eyes",""],
    ["13","😇","smiling face with halo",""],
    ["14","🥰","smiling face with hearts",""],
    ["15","😍","smiling face with heart-eyes",""],
    ["16","🤩","star-struck",""],
    ["17","😘","face blowing a kiss",""],
    ["18","😗","kissing face",""],
    ["19","☺","smiling face",""],
    ["20","😚","kissing face with closed eyes",""],
    ["21","😙","kissing face with smiling eyes",""],
    ["22","🥲","smiling face with tear",""],
    ["23","😋","face savoring food",""],
    ["24","😛","face with tongue",""],
    ["25","😜","winking face with tongue",""],
    ["26","🤪","zany face",""],
    ["27","😝","squinting face with tongue",""],
    ["28","🤑","money-mouth face",""],
    ["29","🤗","hugging face",""],
    ["30","🤭","face with hand over mouth",""],
    ["31","🤫","shushing face",""],
    ["32","🤔","thinking face",""],
    ["33","🤐","zipper-mouth face",""],
    ["34","🤨","face with raised eyebrow",""],
    ["35","😐","neutral face",""],
    ["36","😑","expressionless face",""],
    ["37","😶","face without mouth",""],
    ["38","😶‍🌫️","⊛ face in clouds",""],
    ["39","😏","smirking face",""],
    ["40","😒","unamused face",""],
    ["41","🙄","face with rolling eyes",""],
    ["42","😬","grimacing face",""],
    ["43","😮‍💨","⊛ face exhaling",""],
    ["44","🤥","lying face",""],
    ["45","😌","relieved face",""],
    ["46","😔","pensive face",""],
    ["47","😪","sleepy face",""],
    ["48","🤤","drooling face",""],
    ["49","😴","sleeping face",""],
    ["50","😷","face with medical mask",""],
    ["51","🤒","face with thermometer",""],
    ["52","🤕","face with head-bandage",""],
    ["53","🤢","nauseated face",""],
    ["54","🤮","face vomiting",""],
    ["55","🤧","sneezing face",""],
    ["56","🥵","hot face","overwhelming"],
    ["57","🥶,cold face"," cold",""],
    ["58","🥴","woozy face",""],
    ["59","😵","knocked-out face",""],
    ["60","😵‍💫","⊛ face with spiral eyes",""],
    ["61","🤯,exploding head"," shook",""],
    ["62","🤠","cowboy hat face",""],
    ["63","🥳","partying face",""],
    ["64","🥸","disguised face",""],
    ["65","😎","smiling face with sunglasses",""],
    ["66","🤓","nerd face",""],
    ["67","🧐","face with monocle",""],
    ["68","😕","confused face",""],
    ["69","😟","worried face",""],
    ["70","🙁","slightly frowning face",""],
    ["71","☹","frowning face",""],
    ["72","😮","face with open mouth",""],
    ["73","😯","hushed face",""],
    ["74","😲","astonished face",""],
    ["75","😳","flushed face",""],
    ["76","🥺","pleading face",""],
    ["77","😦","frowning face with open mouth",""],
    ["78","😧","anguished face",""],
    ["79","😨,fearful face"," fear",""],
    ["80","😰","anxious face with sweat",""],
    ["81","😥","sad but relieved face",""],
    ["82","😢","crying face",""],
    ["83","😭","loudly crying face",""],
    ["84","😱","face screaming in fear",""],
    ["85","😖","confounded face",""],
    ["86","😣","persevering face",""],
    ["87","😞","disappointed face",""],
    ["88","😓","downcast face with sweat",""],
    ["89","😩","weary face",""],
    ["90","😫,tired face"," tired",""],
    ["91","🥱,yawning face"," yawning",""],
    ["92","😤,face with steam from nose"," angry",""],
    ["93","😡","pouting face",""],
    ["94","😠","angry face",""],
    ["95","🤬","face with symbols on mouth",""],
    ["96","😈,smiling face with horns"," demon devil",""],
    ["97","👿","angry face with horns",""],
    ["98","💀,skull"," skull",""],
    ["99","☠","skull and crossbones",""],
    ["100","💩","pile of poo",""],
    ["101","🤡","clown face",""],
    ["102","👹","ogre",""],
    ["103","👺","goblin",""],
    ["104","👻","ghost",""],
    ["105","👽","alien",""],
    ["106","👾","alien monster",""],
    ["107","🤖","robot",""],
    ["108","😺","grinning cat",""],
    ["109","😸","grinning cat with smiling eyes",""],
    ["110","😹","cat with tears of joy",""],
    ["111","😻","smiling cat with heart-eyes",""],
    ["112","😼","cat with wry smile",""],
    ["113","😽","kissing cat",""],
    ["114","🙀","weary cat",""],
    ["115","😿","crying cat",""],
    ["116","😾","pouting cat",""],
    ["117","🙈","see-no-evil monkey",""],
    ["118","🙉","hear-no-evil monkey",""],
    ["119","🙊","speak-no-evil monkey",""],
    ["120","💋","kiss mark",""],
    ["121","💌","love letter",""],
    ["122","💘","heart with arrow",""],
    ["123","💝","heart with ribbon",""],
    ["124","💖","sparkling heart",""],
    ["125","💗","growing heart",""],
    ["126","💓","beating heart",""],
    ["127","💞","revolving hearts",""],
    ["128","💕","two hearts",""],
    ["129","💟","heart decoration",""],
    ["130","❣","heart exclamation",""],
    ["131","💔","broken heart",""],
    ["132","❤️‍🔥","⊛ heart on fire",""],
    ["133","❤️‍🩹","⊛ mending heart",""],
    ["134","❤","red heart",""],
    ["135","🧡","orange heart",""],
    ["136","💛","yellow heart",""],
    ["137","💚","green heart",""],
    ["138","💙","blue heart",""],
    ["139","💜","purple heart",""],
    ["140","🤎","brown heart",""],
    ["141","🖤","black heart",""],
    ["142","🤍","white heart",""],
    ["143","💯","hundred points",""],
    ["144","💢","anger symbol",""],
    ["145","💥","collision",""],
    ["146","💫","dizzy",""],
    ["147","💦","sweat droplets",""],
    ["148","💨","dashing away",""],
    ["149","🕳","hole",""],
    ["150","💣","bomb",""],
    ["151","💬","speech balloon",""],
    ["152","👁️‍🗨️","eye in speech bubble",""],
    ["153","🗨","left speech bubble",""],
    ["154","🗯","right anger bubble",""],
    ["155","💭","thought balloon",""],
    ["156","💤","zzz",""],
    ["157","👋","waving hand",""],
    ["158","🤚","raised back of hand",""],
    ["159","🖐","hand with fingers splayed",""],
    ["160","✋","raised hand",""],
    ["161","🖖","vulcan salute",""],
    ["162","👌","OK hand",""],
    ["163","🤌","pinched fingers",""],
    ["164","🤏","pinching hand",""],
    ["165","✌","victory hand",""],
    ["166","🤞","crossed fingers",""],
    ["167","🤟","love-you gesture",""],
    ["168","🤘","sign of the horns",""],
    ["169","🤙","call me hand",""],
    ["170","👈","backhand index pointing left",""],
    ["171","👉","backhand index pointing right",""],
    ["172","👆","backhand index pointing up",""],
    ["173","🖕","middle finger",""],
    ["174","👇","backhand index pointing down",""],
    ["175","☝","index pointing up",""],
    ["176","👍","thumbs up",""],
    ["177","👎","thumbs down",""],
    ["178","✊","raised fist",""],
    ["179","👊","oncoming fist","punch;punched"],
    ["180","🤛","left-facing fist",""],
    ["181","🤜","right-facing fist",""],
    ["182","👏","clapping hands",""],
    ["183","🙌","raising hands",""],
    ["184","👐","open hands",""],
    ["185","🤲","palms up together",""],
    ["186","🤝","handshake",""],
    ["187","🙏","folded hands",""],
    ["188","✍","writing hand",""],
    ["189","💅","nail polish",""],
    ["190","🤳","selfie",""],
    ["191","💪","flexed biceps",""],
    ["192","🦾","mechanical arm",""],
    ["193","🦿","mechanical leg",""],
    ["194","🦵","leg",""],
    ["195","🦶","foot",""],
    ["196","👂","ear",""],
    ["197","🦻","ear with hearing aid",""],
    ["198","👃","nose",""],
    ["199","🧠","brain",""],
    ["200","🫀","anatomical heart",""],
    ["201","🫁","lungs",""],
    ["202","🦷","tooth",""],
    ["203","🦴","bone",""],
    ["204","👀","eyes",""],
    ["205","👁","eye",""],
    ["206","👅","tongue",""],
    ["207","👄","mouth",""],
    ["208","👶","baby","baby"],
    ["209","🧒","child","child"],
    ["210","👦","boy",""],
    ["211","👧","girl",""],
    ["212","🧑","person",""],
    ["213","👱","person: blond hair",""],
    ["214","👨","man",""],
    ["215","🧔","person: beard",""],
    ["216","🧔‍♂️","⊛ man: beard",""],
    ["217","🧔‍♀️","⊛ woman: beard",""],
    ["218","👨‍🦰","man: red hair",""],
    ["219","👨‍🦱","man: curly hair",""],
    ["220","👨‍🦳","man: white hair",""],
    ["221","👨‍🦲","man: bald",""],
    ["222","👩","woman",""],
    ["223","👩‍🦰","woman: red hair",""],
    ["224","🧑‍🦰","person: red hair",""],
    ["225","👩‍🦱","woman: curly hair",""],
    ["226","🧑‍🦱","person: curly hair",""],
    ["227","👩‍🦳","woman: white hair",""],
    ["228","🧑‍🦳","person: white hair",""],
    ["229","👩‍🦲","woman: bald",""],
    ["230","🧑‍🦲","person: bald",""],
    ["231","👱‍♀️","woman: blond hair",""],
    ["232","👱‍♂️","man: blond hair",""],
    ["233","🧓","older person","elderly"],
    ["234","👴","old man",""],
    ["235","👵","old woman",""],
    ["236","🙍","person frowning",""],
    ["237","🙍‍♂️","man frowning",""],
    ["238","🙍‍♀️","woman frowning",""],
    ["239","🙎","person pouting",""],
    ["240","🙎‍♂️","man pouting",""],
    ["241","🙎‍♀️","woman pouting",""],
    ["242","🙅","person gesturing NO",""],
    ["243","🙅‍♂️","man gesturing NO",""],
    ["244","🙅‍♀️","woman gesturing NO",""],
    ["245","🙆","person gesturing OK",""],
    ["246","🙆‍♂️","man gesturing OK",""],
    ["247","🙆‍♀️","woman gesturing OK",""],
    ["248","💁","person tipping hand",""],
    ["249","💁‍♂️","man tipping hand",""],
    ["250","💁‍♀️","woman tipping hand",""],
    ["251","🙋","person raising hand",""],
    ["252","🙋‍♂️","man raising hand",""],
    ["253","🙋‍♀️","woman raising hand",""],
    ["254","🧏","deaf person",""],
    ["255","🧏‍♂️","deaf man",""],
    ["256","🧏‍♀️","deaf woman",""],
    ["257","🙇","person bowing",""],
    ["258","🙇‍♂️","man bowing",""],
    ["259","🙇‍♀️","woman bowing",""],
    ["260","🤦","person facepalming",""],
    ["261","🤦‍♂️","man facepalming",""],
    ["262","🤦‍♀️","woman facepalming",""],
    ["263","🤷","person shrugging",""],
    ["264","🤷‍♂️","man shrugging",""],
    ["265","🤷‍♀️","woman shrugging",""],
    ["266","🧑‍⚕️","health worker",""],
    ["267","👨‍⚕️","man health worker",""],
    ["268","👩‍⚕️","woman health worker",""],
    ["269","🧑‍🎓","student",""],
    ["270","👨‍🎓","man student",""],
    ["271","👩‍🎓","woman student",""],
    ["272","🧑‍🏫","teacher",""],
    ["273","👨‍🏫","man teacher",""],
    ["274","👩‍🏫","woman teacher",""],
    ["275","🧑‍⚖️","judge",""],
    ["276","👨‍⚖️","man judge",""],
    ["277","👩‍⚖️","woman judge",""],
    ["278","🧑‍🌾","farmer",""],
    ["279","👨‍🌾","man farmer",""],
    ["280","👩‍🌾","woman farmer",""],
    ["281","🧑‍🍳","cook",""],
    ["282","👨‍🍳","man cook",""],
    ["283","👩‍🍳","woman cook",""],
    ["284","🧑‍🔧","mechanic",""],
    ["285","👨‍🔧","man mechanic",""],
    ["286","👩‍🔧","woman mechanic",""],
    ["287","🧑‍🏭","factory worker",""],
    ["288","👨‍🏭","man factory worker",""],
    ["289","👩‍🏭","woman factory worker",""],
    ["290","🧑‍💼","office worker",""],
    ["291","👨‍💼","man office worker",""],
    ["292","👩‍💼","woman office worker",""],
    ["293","🧑‍🔬","scientist",""],
    ["294","👨‍🔬","man scientist",""],
    ["295","👩‍🔬","woman scientist",""],
    ["296","🧑‍💻","technologist",""],
    ["297","👨‍💻","man technologist",""],
    ["298","👩‍💻","woman technologist",""],
    ["299","🧑‍🎤","singer",""],
    ["300","👨‍🎤","man singer",""],
    ["301","👩‍🎤","woman singer",""],
    ["302","🧑‍🎨","artist",""],
    ["303","👨‍🎨","man artist",""],
    ["304","👩‍🎨","woman artist",""],
    ["305","🧑‍✈️","pilot",""],
    ["306","👨‍✈️","man pilot",""],
    ["307","👩‍✈️","woman pilot",""],
    ["308","🧑‍🚀","astronaut",""],
    ["309","👨‍🚀","man astronaut",""],
    ["310","👩‍🚀","woman astronaut",""],
    ["311","🧑‍🚒","firefighter","fireman;firefighter"],
    ["312","👨‍🚒","man firefighter",""],
    ["313","👩‍🚒","woman firefighter",""],
    ["314","👮","police officer","police;officer"],
    ["315","👮‍♂️","man police officer",""],
    ["316","👮‍♀️","woman police officer",""],
    ["317","🕵","detective",""],
    ["318","🕵️‍♂️","man detective",""],
    ["319","🕵️‍♀️","woman detective",""],
    ["320","💂","guard",""],
    ["321","💂‍♂️","man guard",""],
    ["322","💂‍♀️","woman guard",""],
    ["323","🥷","ninja",""],
    ["324","👷","construction worker",""],
    ["325","👷‍♂️","man construction worker",""],
    ["326","👷‍♀️","woman construction worker",""],
    ["327","🤴","prince",""],
    ["328","👸","princess",""],
    ["329","👳","person wearing turban",""],
    ["330","👳‍♂️","man wearing turban",""],
    ["331","👳‍♀️","woman wearing turban",""],
    ["332","👲","person with skullcap",""],
    ["333","🧕","woman with headscarf",""],
    ["334","🤵","person in tuxedo",""],
    ["335","🤵‍♂️","man in tuxedo",""],
    ["336","🤵‍♀️","woman in tuxedo",""],
    ["337","👰","person with veil",""],
    ["338","👰‍♂️","man with veil",""],
    ["339","👰‍♀️","woman with veil",""],
    ["340","🤰","pregnant woman",""],
    ["341","🤱","breast-feeding",""],
    ["342","👩‍🍼","woman feeding baby",""],
    ["343","👨‍🍼","man feeding baby",""],
    ["344","🧑‍🍼","person feeding baby",""],
    ["345","👼","baby angel",""],
    ["346","🎅","Santa Claus",""],
    ["347","🤶","Mrs. Claus",""],
    ["348","🧑‍🎄","mx claus",""],
    ["349","🦸","superhero",""],
    ["350","🦸‍♂️","man superhero",""],
    ["351","🦸‍♀️","woman superhero",""],
    ["352","🦹","supervillain",""],
    ["353","🦹‍♂️","man supervillain",""],
    ["354","🦹‍♀️","woman supervillain",""],
    ["355","🧙","mage",""],
    ["356","🧙‍♂️","man mage",""],
    ["357","🧙‍♀️","woman mage",""],
    ["358","🧚","fairy",""],
    ["359","🧚‍♂️","man fairy",""],
    ["360","🧚‍♀️","woman fairy",""],
    ["361","🧛","vampire",""],
    ["362","🧛‍♂️","man vampire",""],
    ["363","🧛‍♀️","woman vampire",""],
    ["364","🧜","merperson",""],
    ["365","🧜‍♂️","merman",""],
    ["366","🧜‍♀️","mermaid",""],
    ["367","🧝","elf",""],
    ["368","🧝‍♂️","man elf",""],
    ["369","🧝‍♀️","woman elf",""],
    ["370","🧞","genie",""],
    ["371","🧞‍♂️","man genie",""],
    ["372","🧞‍♀️","woman genie",""],
    ["373","🧟","zombie",""],
    ["374","🧟‍♂️","man zombie",""],
    ["375","🧟‍♀️","woman zombie",""],
    ["376","💆","person getting massage",""],
    ["377","💆‍♂️","man getting massage",""],
    ["378","💆‍♀️","woman getting massage",""],
    ["379","💇","person getting haircut",""],
    ["380","💇‍♂️","man getting haircut",""],
    ["381","💇‍♀️","woman getting haircut",""],
    ["382","🚶","person walking",""],
    ["383","🚶‍♂️","man walking",""],
    ["384","🚶‍♀️","woman walking",""],
    ["385","🧍","person standing",""],
    ["386","🧍‍♂️","man standing",""],
    ["387","🧍‍♀️","woman standing",""],
    ["388","🧎","person kneeling",""],
    ["389","🧎‍♂️","man kneeling",""],
    ["390","🧎‍♀️","woman kneeling",""],
    ["391","🧑‍🦯","person with white cane",""],
    ["392","👨‍🦯","man with white cane",""],
    ["393","👩‍🦯","woman with white cane",""],
    ["394","🧑‍🦼","person in motorized wheelchair",""],
    ["395","👨‍🦼","man in motorized wheelchair",""],
    ["396","👩‍🦼","woman in motorized wheelchair",""],
    ["397","🧑‍🦽","person in manual wheelchair",""],
    ["398","👨‍🦽","man in manual wheelchair",""],
    ["399","👩‍🦽","woman in manual wheelchair",""],
    ["400","🏃","person running",""],
    ["401","🏃‍♂️","man running",""],
    ["402","🏃‍♀️","woman running",""],
    ["403","💃","woman dancing",""],
    ["404","🕺","man dancing",""],
    ["405","🕴","person in suit levitating",""],
    ["406","👯","people with bunny ears",""],
    ["407","👯‍♂️","men with bunny ears",""],
    ["408","👯‍♀️","women with bunny ears",""],
    ["409","🧖","person in steamy room",""],
    ["410","🧖‍♂️","man in steamy room",""],
    ["411","🧖‍♀️","woman in steamy room",""],
    ["412","🧗","person climbing",""],
    ["413","🧗‍♂️","man climbing",""],
    ["414","🧗‍♀️","woman climbing",""],
    ["415","🤺","person fencing",""],
    ["416","🏇","horse racing",""],
    ["417","⛷","skier",""],
    ["418","🏂","snowboarder",""],
    ["419","🏌","person golfing",""],
    ["420","🏌️‍♂️","man golfing",""],
    ["421","🏌️‍♀️","woman golfing",""],
    ["422","🏄","person surfing",""],
    ["423","🏄‍♂️","man surfing",""],
    ["424","🏄‍♀️","woman surfing",""],
    ["425","🚣","person rowing boat",""],
    ["426","🚣‍♂️","man rowing boat",""],
    ["427","🚣‍♀️","woman rowing boat",""],
    ["428","🏊","person swimming",""],
    ["429","🏊‍♂️","man swimming",""],
    ["430","🏊‍♀️","woman swimming",""],
    ["431","⛹","person bouncing ball",""],
    ["432","⛹️‍♂️","man bouncing ball",""],
    ["433","⛹️‍♀️","woman bouncing ball",""],
    ["434","🏋","person lifting weights",""],
    ["435","🏋️‍♂️","man lifting weights",""],
    ["436","🏋️‍♀️","woman lifting weights",""],
    ["437","🚴","person biking",""],
    ["438","🚴‍♂️","man biking",""],
    ["439","🚴‍♀️","woman biking",""],
    ["440","🚵","person mountain biking",""],
    ["441","🚵‍♂️","man mountain biking",""],
    ["442","🚵‍♀️","woman mountain biking",""],
    ["443","🤸","person cartwheeling",""],
    ["444","🤸‍♂️","man cartwheeling",""],
    ["445","🤸‍♀️","woman cartwheeling",""],
    ["446","🤼","people wrestling",""],
    ["447","🤼‍♂️","men wrestling",""],
    ["448","🤼‍♀️","women wrestling",""],
    ["449","🤽","person playing water polo",""],
    ["450","🤽‍♂️","man playing water polo",""],
    ["451","🤽‍♀️","woman playing water polo",""],
    ["452","🤾","person playing handball",""],
    ["453","🤾‍♂️","man playing handball",""],
    ["454","🤾‍♀️","woman playing handball",""],
    ["455","🤹","person juggling",""],
    ["456","🤹‍♂️","man juggling",""],
    ["457","🤹‍♀️","woman juggling",""],
    ["458","🧘","person in lotus position",""],
    ["459","🧘‍♂️","man in lotus position",""],
    ["460","🧘‍♀️","woman in lotus position",""],
    ["461","🛀","person taking bath",""],
    ["462","🛌","person in bed",""],
    ["463","🧑‍🤝‍🧑","people holding hands",""],
    ["464","👭","women holding hands",""],
    ["465","👫","woman and man holding hands",""],
    ["466","👬","men holding hands",""],
    ["467","💏","kiss","kiss"],
    ["471","💑","couple with heart","couple"],
    ["475","👪","family","family"],
    ["501","🗣","speaking head",""],
    ["502","👤","bust in silhouette",""],
    ["503","👥","busts in silhouette",""],
    ["504","🫂","people hugging",""],
    ["505","👣","footprints",""],
    ["506","🦰","red hair",""],
    ["507","🦱","curly hair",""],
    ["508","🦳","white hair",""],
    ["509","🦲","bald",""],
    ["510","🐵","monkey face",""],
    ["511","🐒","monkey",""],
    ["512","🦍","gorilla",""],
    ["513","🦧","orangutan",""],
    ["514","🐶","dog face",""],
    ["515","🐕","dog",""],
    ["516","🦮","guide dog",""],
    ["517","🐕‍🦺","service dog",""],
    ["518","🐩","poodle",""],
    ["519","🐺","wolf",""],
    ["520","🦊","fox",""],
    ["521","🦝","raccoon",""],
    ["522","🐱","cat face",""],
    ["523","🐈","cat",""],
    ["524","🐈‍⬛","black cat",""],
    ["525","🦁","lion",""],
    ["526","🐯","tiger face",""],
    ["527","🐅","tiger",""],
    ["528","🐆","leopard",""],
    ["529","🐴","horse face",""],
    ["530","🐎","horse",""],
    ["531","🦄","unicorn",""],
    ["532","🦓","zebra",""],
    ["533","🦌","deer",""],
    ["534","🦬","bison",""],
    ["535","🐮","cow face",""],
    ["536","🐂","ox",""],
    ["537","🐃","water buffalo",""],
    ["538","🐄","cow",""],
    ["539","🐷","pig face",""],
    ["540","🐖","pig",""],
    ["541","🐗","boar",""],
    ["542","🐽","pig nose",""],
    ["543","🐏","ram",""],
    ["544","🐑","ewe",""],
    ["545","🐐","goat",""],
    ["546","🐪","camel",""],
    ["547","🐫","two-hump camel",""],
    ["548","🦙","llama",""],
    ["549","🦒","giraffe",""],
    ["550","🐘","elephant",""],
    ["551","🦣","mammoth",""],
    ["552","🦏","rhinoceros",""],
    ["553","🦛","hippopotamus",""],
    ["554","🐭","mouse face",""],
    ["555","🐁","mouse",""],
    ["556","🐀","rat",""],
    ["557","🐹","hamster",""],
    ["558","🐰","rabbit face",""],
    ["559","🐇","rabbit",""],
    ["560","🐿","chipmunk",""],
    ["561","🦫","beaver",""],
    ["562","🦔","hedgehog",""],
    ["563","🦇","bat",""],
    ["564","🐻","bear",""],
    ["565","🐻‍❄️","polar bear",""],
    ["566","🐨","koala",""],
    ["567","🐼","panda",""],
    ["568","🦥","sloth",""],
    ["569","🦦","otter",""],
    ["570","🦨","skunk",""],
    ["571","🦘","kangaroo",""],
    ["572","🦡","badger",""],
    ["573","🐾","paw prints",""],
    ["574","🦃","turkey",""],
    ["575","🐔","chicken",""],
    ["576","🐓","rooster",""],
    ["577","🐣","hatching chick",""],
    ["578","🐤","baby chick",""],
    ["579","🐥","front-facing baby chick",""],
    ["580","🐦","bird",""],
    ["581","🐧","penguin",""],
    ["582","🕊","dove",""],
    ["583","🦅","eagle",""],
    ["584","🦆","duck",""],
    ["585","🦢","swan",""],
    ["586","🦉","owl",""],
    ["587","🦤","dodo",""],
    ["588","🪶","feather",""],
    ["589","🦩","flamingo",""],
    ["590","🦚","peacock",""],
    ["591","🦜","parrot",""],
    ["592","🐸","frog",""],
    ["593","🐊","crocodile",""],
    ["594","🐢","turtle",""],
    ["595","🦎","lizard",""],
    ["596","🐍","snake",""],
    ["597","🐲","dragon face",""],
    ["598","🐉","dragon",""],
    ["599","🦕","sauropod",""],
    ["600","🦖","T-Rex",""],
    ["601","🐳","spouting whale",""],
    ["602","🐋","whale",""],
    ["603","🐬","dolphin",""],
    ["604","🦭","seal",""],
    ["605","🐟","fish",""],
    ["606","🐠","tropical fish",""],
    ["607","🐡","blowfish",""],
    ["608","🦈","shark",""],
    ["609","🐙","octopus",""],
    ["610","🐚","spiral shell",""],
    ["611","🐌","snail",""],
    ["612","🦋","butterfly",""],
    ["613","🐛","bug",""],
    ["614","🐜","ant",""],
    ["615","🐝","honeybee",""],
    ["616","🪲","beetle",""],
    ["617","🐞","lady beetle",""],
    ["618","🦗","cricket",""],
    ["619","🪳","cockroach",""],
    ["620","🕷","spider",""],
    ["621","🕸","spider web",""],
    ["622","🦂","scorpion",""],
    ["623","🦟","mosquito",""],
    ["624","🪰","fly",""],
    ["625","🪱","worm",""],
    ["626","🦠","microbe",""],
    ["627","💐","bouquet",""],
    ["628","🌸","cherry blossom",""],
    ["629","💮","white flower",""],
    ["630","🏵","rosette",""],
    ["631","🌹","rose",""],
    ["632","🥀","wilted flower",""],
    ["633","🌺","hibiscus",""],
    ["634","🌻","sunflower",""],
    ["635","🌼","blossom",""],
    ["636","🌷","tulip",""],
    ["637","🌱","seedling",""],
    ["638","🪴","potted plant",""],
    ["639","🌲","evergreen tree",""],
    ["640","🌳","deciduous tree",""],
    ["641","🌴","palm tree",""],
    ["642","🌵","cactus",""],
    ["643","🌾","sheaf of rice",""],
    ["644","🌿","herb",""],
    ["645","☘","shamrock",""],
    ["646","🍀","four leaf clover",""],
    ["647","🍁","maple leaf",""],
    ["648","🍂","fallen leaf",""],
    ["649","🍃","leaf fluttering in wind",""],
    ["650","🍇","grapes",""],
    ["651","🍈","melon",""],
    ["652","🍉","watermelon",""],
    ["653","🍊","tangerine",""],
    ["654","🍋","lemon",""],
    ["655","🍌","banana",""],
    ["656","🍍","pineapple",""],
    ["657","🥭","mango",""],
    ["658","🍎","red apple",""],
    ["659","🍏","green apple",""],
    ["660","🍐","pear",""],
    ["661","🍑","peach",""],
    ["662","🍒","cherries",""],
    ["663","🍓","strawberry",""],
    ["664","🫐","blueberries",""],
    ["665","🥝","kiwi fruit",""],
    ["666","🍅","tomato",""],
    ["667","🫒","olive",""],
    ["668","🥥","coconut",""],
    ["669","🥑","avocado",""],
    ["670","🍆","eggplant",""],
    ["671","🥔","potato",""],
    ["672","🥕","carrot",""],
    ["673","🌽","ear of corn",""],
    ["674","🌶","hot pepper",""],
    ["675","🫑","bell pepper",""],
    ["676","🥒","cucumber",""],
    ["677","🥬","leafy green",""],
    ["678","🥦","broccoli",""],
    ["679","🧄","garlic",""],
    ["680","🧅","onion",""],
    ["681","🍄","mushroom",""],
    ["682","🥜","peanuts",""],
    ["683","🌰","chestnut",""],
    ["684","🍞","bread",""],
    ["685","🥐","croissant",""],
    ["686","🥖","baguette bread",""],
    ["687","🫓","flatbread",""],
    ["688","🥨","pretzel",""],
    ["689","🥯","bagel",""],
    ["690","🥞","pancakes",""],
    ["691","🧇","waffle",""],
    ["692","🧀","cheese wedge",""],
    ["693","🍖","meat on bone",""],
    ["694","🍗","poultry leg",""],
    ["695","🥩","cut of meat",""],
    ["696","🥓","bacon",""],
    ["697","🍔","hamburger",""],
    ["698","🍟","french fries",""],
    ["699","🍕","pizza",""],
    ["700","🌭","hot dog",""],
    ["701","🥪","sandwich",""],
    ["702","🌮","taco",""],
    ["703","🌯","burrito",""],
    ["704","🫔","tamale",""],
    ["705","🥙","stuffed flatbread",""],
    ["706","🧆","falafel",""],
    ["707","🥚","egg",""],
    ["708","🍳","cooking",""],
    ["709","🥘","shallow pan of food",""],
    ["710","🍲","pot of food",""],
    ["711","🫕","fondue",""],
    ["712","🥣","bowl with spoon",""],
    ["713","🥗","green salad",""],
    ["714","🍿","popcorn",""],
    ["715","🧈","butter",""],
    ["716","🧂","salt",""],
    ["717","🥫","canned food",""],
    ["718","🍱","bento box",""],
    ["719","🍘","rice cracker",""],
    ["720","🍙","rice ball",""],
    ["721","🍚","cooked rice",""],
    ["722","🍛","curry rice",""],
    ["723","🍜","steaming bowl",""],
    ["724","🍝","spaghetti",""],
    ["725","🍠","roasted sweet potato",""],
    ["726","🍢","oden",""],
    ["727","🍣","sushi",""],
    ["728","🍤","fried shrimp",""],
    ["729","🍥","fish cake with swirl",""],
    ["730","🥮","moon cake",""],
    ["731","🍡","dango",""],
    ["732","🥟","dumpling",""],
    ["733","🥠","fortune cookie",""],
    ["734","🥡","takeout box",""],
    ["735","🦀","crab",""],
    ["736","🦞","lobster",""],
    ["737","🦐","shrimp",""],
    ["738","🦑","squid",""],
    ["739","🦪","oyster",""],
    ["740","🍦","soft ice cream",""],
    ["741","🍧","shaved ice",""],
    ["742","🍨","ice cream",""],
    ["743","🍩","doughnut",""],
    ["744","🍪","cookie",""],
    ["745","🎂","birthday cake","birthday"],
    ["746","🍰","shortcake",""],
    ["747","🧁","cupcake","cupcake"],
    ["748","🥧","pie",""],
    ["749","🍫","chocolate bar","chocolate"],
    ["750","🍬","candy","candy"],
    ["751","🍭","lollipop",""],
    ["752","🍮","custard",""],
    ["753","🍯","honey pot",""],
    ["754","🍼","baby bottle",""],
    ["755","🥛","glass of milk",""],
    ["756","☕","hot beverage",""],
    ["757","🫖","teapot",""],
    ["758","🍵","teacup without handle",""],
    ["759","🍶","sake",""],
    ["760","🍾","bottle with popping cork",""],
    ["761","🍷","wine glass",""],
    ["762","🍸","cocktail glass",""],
    ["763","🍹","tropical drink",""],
    ["764","🍺","beer mug",""],
    ["765","🍻","clinking beer mugs",""],
    ["766","🥂","clinking glasses",""],
    ["767","🥃","tumbler glass",""],
    ["768","🥤","cup with straw",""],
    ["769","🧋","bubble tea",""],
    ["770","🧃","beverage box",""],
    ["771","🧉","mate",""],
    ["772","🧊","ice",""],
    ["773","🥢","chopsticks",""],
    ["774","🍽","fork and knife with plate",""],
    ["775","🍴","fork and knife",""],
    ["776","🥄","spoon",""],
    ["777","🔪","kitchen knife",""],
    ["778","🏺","amphora",""],
    ["779","🌍","globe showing Europe-Africa",""],
    ["780","🌎","globe showing Americas",""],
    ["781","🌏","globe showing Asia-Australia",""],
    ["782","🌐","globe with meridians",""],
    ["783","🗺","world map",""],
    ["784","🗾","map of Japan",""],
    ["785","🧭","compass",""],
    ["786","🏔","snow-capped mountain",""],
    ["787","⛰","mountain",""],
    ["788","🌋","volcano",""],
    ["789","🗻","mount fuji",""],
    ["790","🏕","camping",""],
    ["791","🏖","beach with umbrella",""],
    ["792","🏜","desert",""],
    ["793","🏝","desert island",""],
    ["794","🏞","national park",""],
    ["795","🏟","stadium",""],
    ["796","🏛","classical building",""],
    ["797","🏗","building construction",""],
    ["798","🧱","brick",""],
    ["799","🪨","rock",""],
    ["800","🪵","wood",""],
    ["801","🛖","hut",""],
    ["802","🏘","houses",""],
    ["803","🏚","derelict house",""],
    ["804","🏠","house",""],
    ["805","🏡","house with garden",""],
    ["806","🏢","office building",""],
    ["807","🏣","Japanese post office",""],
    ["808","🏤","post office",""],
    ["809","🏥","hospital",""],
    ["810","🏦","bank",""],
    ["811","🏨","hotel",""],
    ["812","🏩","love hotel",""],
    ["813","🏪","convenience store",""],
    ["814","🏫","school",""],
    ["815","🏬","department store",""],
    ["816","🏭","factory",""],
    ["817","🏯","Japanese castle",""],
    ["818","🏰","castle",""],
    ["819","💒","wedding",""],
    ["820","🗼","Tokyo tower",""],
    ["821","🗽","Statue of Liberty",""],
    ["822","⛪","church",""],
    ["823","🕌","mosque",""],
    ["824","🛕","hindu temple",""],
    ["825","🕍","synagogue",""],
    ["826","⛩","shinto shrine",""],
    ["827","🕋","kaaba",""],
    ["828","⛲","fountain",""],
    ["829","⛺","tent",""],
    ["830","🌁","foggy",""],
    ["831","🌃","night with stars",""],
    ["832","🏙","cityscape",""],
    ["833","🌄","sunrise over mountains",""],
    ["834","🌅","sunrise",""],
    ["835","🌆","cityscape at dusk",""],
    ["836","🌇","sunset",""],
    ["837","🌉","bridge at night",""],
    ["838","♨","hot springs",""],
    ["839","🎠","carousel horse",""],
    ["840","🎡","ferris wheel",""],
    ["841","🎢","roller coaster",""],
    ["842","💈","barber pole",""],
    ["843","🎪","circus tent",""],
    ["844","🚂","locomotive",""],
    ["845","🚃","railway car",""],
    ["846","🚄","high-speed train",""],
    ["847","🚅","bullet train",""],
    ["848","🚆","train",""],
    ["849","🚇","metro",""],
    ["850","🚈","light rail",""],
    ["851","🚉","station",""],
    ["852","🚊","tram",""],
    ["853","🚝","monorail",""],
    ["854","🚞","mountain railway",""],
    ["855","🚋","tram car",""],
    ["856","🚌","bus",""],
    ["857","🚍","oncoming bus",""],
    ["858","🚎","trolleybus",""],
    ["859","🚐","minibus",""],
    ["860","🚑","ambulance",""],
    ["861","🚒","fire engine",""],
    ["862","🚓","police car",""],
    ["863","🚔","oncoming police car",""],
    ["864","🚕","taxi",""],
    ["865","🚖","oncoming taxi",""],
    ["866","🚗","automobile",""],
    ["867","🚘","oncoming automobile",""],
    ["868","🚙","sport utility vehicle",""],
    ["869","🛻","pickup truck",""],
    ["870","🚚","delivery truck",""],
    ["871","🚛","articulated lorry",""],
    ["872","🚜","tractor",""],
    ["873","🏎","racing car",""],
    ["874","🏍","motorcycle",""],
    ["875","🛵","motor scooter",""],
    ["876","🦽","manual wheelchair",""],
    ["877","🦼","motorized wheelchair",""],
    ["878","🛺","auto rickshaw",""],
    ["879","🚲","bicycle",""],
    ["880","🛴","kick scooter",""],
    ["881","🛹","skateboard",""],
    ["882","🛼","roller skate",""],
    ["883","🚏","bus stop",""],
    ["884","🛣","motorway",""],
    ["885","🛤","railway track",""],
    ["886","🛢","oil drum",""],
    ["887","⛽","fuel pump",""],
    ["888","🚨","police car light",""],
    ["889","🚥","horizontal traffic light",""],
    ["890","🚦","vertical traffic light",""],
    ["891","🛑","stop sign",""],
    ["892","🚧","construction",""],
    ["893","⚓","anchor",""],
    ["894","⛵","sailboat",""],
    ["895","🛶","canoe",""],
    ["896","🚤","speedboat",""],
    ["897","🛳","passenger ship",""],
    ["898","⛴","ferry",""],
    ["899","🛥","motor boat",""],
    ["900","🚢","ship",""],
    ["901","✈","airplane",""],
    ["902","🛩","small airplane",""],
    ["903","🛫","airplane departure",""],
    ["904","🛬","airplane arrival",""],
    ["905","🪂","parachute",""],
    ["906","💺","seat",""],
    ["907","🚁","helicopter",""],
    ["908","🚟","suspension railway",""],
    ["909","🚠","mountain cableway",""],
    ["910","🚡","aerial tramway",""],
    ["911","🛰","satellite",""],
    ["912","🚀","rocket",""],
    ["913","🛸","flying saucer",""],
    ["914","🛎","bellhop bell",""],
    ["915","🧳","luggage",""],
    ["916","⌛","hourglass done",""],
    ["917","⏳","hourglass not done",""],
    ["918","⌚","watch",""],
    ["919","⏰","alarm clock",""],
    ["920","⏱","stopwatch",""],
    ["921","⏲","timer clock",""],
    ["922","🕰","mantelpiece clock",""],
    ["923","🕛","twelve o’clock",""],
    ["924","🕧","twelve-thirty",""],
    ["925","🕐","one o’clock",""],
    ["926","🕜","one-thirty",""],
    ["927","🕑","two o’clock",""],
    ["928","🕝","two-thirty",""],
    ["929","🕒","three o’clock",""],
    ["930","🕞","three-thirty",""],
    ["931","🕓","four o’clock",""],
    ["932","🕟","four-thirty",""],
    ["933","🕔","five o’clock",""],
    ["934","🕠","five-thirty",""],
    ["935","🕕","six o’clock",""],
    ["936","🕡","six-thirty",""],
    ["937","🕖","seven o’clock",""],
    ["938","🕢","seven-thirty",""],
    ["939","🕗","eight o’clock",""],
    ["940","🕣","eight-thirty",""],
    ["941","🕘","nine o’clock",""],
    ["942","🕤","nine-thirty",""],
    ["943","🕙","ten o’clock",""],
    ["944","🕥","ten-thirty",""],
    ["945","🕚","eleven o’clock",""],
    ["946","🕦","eleven-thirty",""],
    ["947","🌑","new moon",""],
    ["948","🌒","waxing crescent moon",""],
    ["949","🌓","first quarter moon",""],
    ["950","🌔","waxing gibbous moon",""],
    ["951","🌕","full moon",""],
    ["952","🌖","waning gibbous moon",""],
    ["953","🌗","last quarter moon",""],
    ["954","🌘","waning crescent moon",""],
    ["955","🌙","crescent moon",""],
    ["956","🌚","new moon face",""],
    ["957","🌛","first quarter moon face",""],
    ["958","🌜","last quarter moon face",""],
    ["959","🌡","thermometer",""],
    ["960","☀","sun",""],
    ["961","🌝","full moon face",""],
    ["962","🌞","sun with face",""],
    ["963","🪐","ringed planet",""],
    ["964","⭐","star",""],
    ["965","🌟","glowing star",""],
    ["966","🌠","shooting star",""],
    ["967","🌌","milky way",""],
    ["968","☁","cloud",""],
    ["969","⛅","sun behind cloud",""],
    ["970","⛈","cloud with lightning and rain",""],
    ["971","🌤","sun behind small cloud",""],
    ["972","🌥","sun behind large cloud",""],
    ["973","🌦","sun behind rain cloud",""],
    ["974","🌧","cloud with rain",""],
    ["975","🌨","cloud with snow",""],
    ["976","🌩","cloud with lightning",""],
    ["977","🌪","tornado",""],
    ["978","🌫","fog",""],
    ["979","🌬","wind face",""],
    ["980","🌀","cyclone",""],
    ["981","🌈","rainbow",""],
    ["982","🌂","closed umbrella",""],
    ["983","☂","umbrella",""],
    ["984","☔","umbrella with rain drops",""],
    ["985","⛱","umbrella on ground",""],
    ["986","⚡","high voltage",""],
    ["987","❄","snowflake",""],
    ["988","☃","snowman",""],
    ["989","⛄","snowman without snow",""],
    ["990","☄","comet",""],
    ["991","🔥","fire",""],
    ["992","💧","droplet",""],
    ["993","🌊","water wave",""],
    ["994","🎃","jack-o-lantern",""],
    ["995","🎄","Christmas tree",""],
    ["996","🎆","fireworks",""],
    ["997","🎇","sparkler",""],
    ["998","🧨","firecracker",""],
    ["999","✨","sparkles",""],
    ["1000","🎈","balloon",""],
    ["1001","🎉","party popper",""],
    ["1002","🎊","confetti ball",""],
    ["1003","🎋","tanabata tree",""],
    ["1004","🎍","pine decoration",""],
    ["1005","🎎","Japanese dolls",""],
    ["1006","🎏","carp streamer",""],
    ["1007","🎐","wind chime",""],
    ["1008","🎑","moon viewing ceremony",""],
    ["1009","🧧","red envelope",""],
    ["1010","🎀","ribbon",""],
    ["1011","🎁","wrapped gift",""],
    ["1012","🎗","reminder ribbon",""],
    ["1013","🎟","admission tickets",""],
    ["1014","🎫","ticket",""],
    ["1015","🎖","military medal",""],
    ["1016","🏆","trophy",""],
    ["1017","🏅","sports medal",""],
    ["1018","🥇","1st place medal",""],
    ["1019","🥈","2nd place medal",""],
    ["1020","🥉","3rd place medal",""],
    ["1021","⚽","soccer ball",""],
    ["1022","⚾","baseball",""],
    ["1023","🥎","softball",""],
    ["1024","🏀","basketball",""],
    ["1025","🏐","volleyball",""],
    ["1026","🏈","american football",""],
    ["1027","🏉","rugby football",""],
    ["1028","🎾","tennis",""],
    ["1029","🥏","flying disc",""],
    ["1030","🎳","bowling",""],
    ["1031","🏏","cricket game",""],
    ["1032","🏑","field hockey",""],
    ["1033","🏒","ice hockey",""],
    ["1034","🥍","lacrosse",""],
    ["1035","🏓","ping pong",""],
    ["1036","🏸","badminton",""],
    ["1037","🥊","boxing glove",""],
    ["1038","🥋","martial arts uniform",""],
    ["1039","🥅","goal net",""],
    ["1040","⛳","flag in hole",""],
    ["1041","⛸","ice skate",""],
    ["1042","🎣","fishing pole",""],
    ["1043","🤿","diving mask",""],
    ["1044","🎽","running shirt",""],
    ["1045","🎿","skis",""],
    ["1046","🛷","sled",""],
    ["1047","🥌","curling stone",""],
    ["1048","🎯","bullseye",""],
    ["1049","🪀","yo-yo",""],
    ["1050","🪁","kite",""],
    ["1051","🎱","pool 8 ball",""],
    ["1052","🔮","crystal ball",""],
    ["1053","🪄","magic wand",""],
    ["1054","🧿","nazar amulet",""],
    ["1055","🎮","video game",""],
    ["1056","🕹","joystick",""],
    ["1057","🎰","slot machine",""],
    ["1058","🎲","game die",""],
    ["1059","🧩","puzzle piece",""],
    ["1060","🧸","teddy bear",""],
    ["1061","🪅","piñata",""],
    ["1062","🪆","nesting dolls",""],
    ["1063","♠","spade suit",""],
    ["1064","♥","heart suit",""],
    ["1065","♦","diamond suit",""],
    ["1066","♣","club suit",""],
    ["1067","♟","chess pawn",""],
    ["1068","🃏","joker",""],
    ["1069","🀄","mahjong red dragon",""],
    ["1070","🎴","flower playing cards",""],
    ["1071","🎭","performing arts",""],
    ["1072","🖼","framed picture",""],
    ["1073","🎨","artist palette",""],
    ["1074","🧵","thread",""],
    ["1075","🪡","sewing needle",""],
    ["1076","🧶","yarn",""],
    ["1077","🪢","knot",""],
    ["1078","👓","glasses",""],
    ["1079","🕶","sunglasses",""],
    ["1080","🥽","goggles",""],
    ["1081","🥼","lab coat",""],
    ["1082","🦺","safety vest",""],
    ["1083","👔","necktie",""],
    ["1084","👕","t-shirt",""],
    ["1085","👖","jeans",""],
    ["1086","🧣","scarf",""],
    ["1087","🧤","gloves",""],
    ["1088","🧥","coat",""],
    ["1089","🧦","socks",""],
    ["1090","👗","dress",""],
    ["1091","👘","kimono",""],
    ["1092","🥻","sari",""],
    ["1093","🩱","one-piece swimsuit",""],
    ["1094","🩲","briefs",""],
    ["1095","🩳","shorts",""],
    ["1096","👙","bikini",""],
    ["1097","👚","woman’s clothes",""],
    ["1098","👛","purse",""],
    ["1099","👜","handbag",""],
    ["1100","👝","clutch bag",""],
    ["1101","🛍","shopping bags",""],
    ["1102","🎒","backpack",""],
    ["1103","🩴","thong sandal",""],
    ["1104","👞","man’s shoe",""],
    ["1105","👟","running shoe",""],
    ["1106","🥾","hiking boot",""],
    ["1107","🥿","flat shoe",""],
    ["1108","👠","high-heeled shoe",""],
    ["1109","👡","woman’s sandal",""],
    ["1110","🩰","ballet shoes",""],
    ["1111","👢","woman’s boot",""],
    ["1112","👑","crown",""],
    ["1113","👒","woman’s hat",""],
    ["1114","🎩","top hat",""],
    ["1115","🎓","graduation cap",""],
    ["1116","🧢","billed cap",""],
    ["1117","🪖","military helmet",""],
    ["1118","⛑","rescue worker’s helmet",""],
    ["1119","📿","prayer beads",""],
    ["1120","💄","lipstick",""],
    ["1121","💍","ring",""],
    ["1122","💎","gem stone",""],
    ["1123","🔇","muted speaker",""],
    ["1124","🔈","speaker low volume",""],
    ["1125","🔉","speaker medium volume",""],
    ["1126","🔊","speaker high volume",""],
    ["1127","📢","loudspeaker",""],
    ["1128","📣","megaphone",""],
    ["1129","📯","postal horn",""],
    ["1130","🔔","bell",""],
    ["1131","🔕","bell with slash",""],
    ["1132","🎼","musical score",""],
    ["1133","🎵","musical note",""],
    ["1134","🎶","musical notes",""],
    ["1135","🎙","studio microphone",""],
    ["1136","🎚","level slider",""],
    ["1137","🎛","control knobs",""],
    ["1138","🎤","microphone",""],
    ["1139","🎧","headphone",""],
    ["1140","📻","radio",""],
    ["1141","🎷","saxophone",""],
    ["1142","🪗","accordion",""],
    ["1143","🎸","guitar",""],
    ["1144","🎹","musical keyboard",""],
    ["1145","🎺","trumpet",""],
    ["1146","🎻","violin",""],
    ["1147","🪕","banjo",""],
    ["1148","🥁","drum",""],
    ["1149","🪘","long drum",""],
    ["1150","📱","mobile phone",""],
    ["1151","📲","mobile phone with arrow",""],
    ["1152","☎","telephone",""],
    ["1153","📞","telephone receiver",""],
    ["1154","📟","pager",""],
    ["1155","📠","fax machine",""],
    ["1156","🔋","battery",""],
    ["1157","🔌","electric plug",""],
    ["1158","💻","laptop",""],
    ["1159","🖥","desktop computer",""],
    ["1160","🖨","printer",""],
    ["1161","⌨","keyboard",""],
    ["1162","🖱","computer mouse",""],
    ["1163","🖲","trackball",""],
    ["1164","💽","computer disk",""],
    ["1165","💾","floppy disk",""],
    ["1166","💿","optical disk",""],
    ["1167","📀","dvd",""],
    ["1168","🧮","abacus",""],
    ["1169","🎥","movie camera",""],
    ["1170","🎞","film frames",""],
    ["1171","📽","film projector",""],
    ["1172","🎬","clapper board",""],
    ["1173","📺","television",""],
    ["1174","📷","camera",""],
    ["1175","📸","camera with flash",""],
    ["1176","📹","video camera",""],
    ["1177","📼","videocassette",""],
    ["1178","🔍","magnifying glass tilted left",""],
    ["1179","🔎","magnifying glass tilted right",""],
    ["1180","🕯","candle",""],
    ["1181","💡","light bulb",""],
    ["1182","🔦","flashlight",""],
    ["1183","🏮","red paper lantern",""],
    ["1184","🪔","diya lamp",""],
    ["1185","📔","notebook with decorative cover",""],
    ["1186","📕","closed book",""],
    ["1187","📖","open book",""],
    ["1188","📗","green book",""],
    ["1189","📘","blue book",""],
    ["1190","📙","orange book",""],
    ["1191","📚","books",""],
    ["1192","📓","notebook",""],
    ["1193","📒","ledger",""],
    ["1194","📃","page with curl",""],
    ["1195","📜","scroll",""],
    ["1196","📄","page facing up",""],
    ["1197","📰","newspaper",""],
    ["1198","🗞","rolled-up newspaper",""],
    ["1199","📑","bookmark tabs",""],
    ["1200","🔖","bookmark",""],
    ["1201","🏷","label",""],
    ["1202","💰","money bag",""],
    ["1203","🪙","coin",""],
    ["1204","💴","yen banknote",""],
    ["1205","💵","dollar banknote",""],
    ["1206","💶","euro banknote",""],
    ["1207","💷","pound banknote",""],
    ["1208","💸","money with wings",""],
    ["1209","💳","credit card",""],
    ["1210","🧾","receipt",""],
    ["1211","💹","chart increasing with yen",""],
    ["1212","✉","envelope",""],
    ["1213","📧","e-mail",""],
    ["1214","📨","incoming envelope",""],
    ["1215","📩","envelope with arrow",""],
    ["1216","📤","outbox tray",""],
    ["1217","📥","inbox tray",""],
    ["1218","📦","package",""],
    ["1219","📫","closed mailbox with raised flag",""],
    ["1220","📪","closed mailbox with lowered flag",""],
    ["1221","📬","open mailbox with raised flag",""],
    ["1222","📭","open mailbox with lowered flag",""],
    ["1223","📮","postbox",""],
    ["1224","🗳","ballot box with ballot",""],
    ["1225","✏","pencil",""],
    ["1226","✒","black nib",""],
    ["1227","🖋","fountain pen",""],
    ["1228","🖊","pen",""],
    ["1229","🖌","paintbrush",""],
    ["1230","🖍","crayon",""],
    ["1231","📝","memo",""],
    ["1232","💼","briefcase",""],
    ["1233","📁","file folder",""],
    ["1234","📂","open file folder",""],
    ["1235","🗂","card index dividers",""],
    ["1236","📅","calendar",""],
    ["1237","📆","tear-off calendar",""],
    ["1238","🗒","spiral notepad",""],
    ["1239","🗓","spiral calendar",""],
    ["1240","📇","card index",""],
    ["1241","📈","chart increasing",""],
    ["1242","📉","chart decreasing",""],
    ["1243","📊","bar chart",""],
    ["1244","📋","clipboard",""],
    ["1245","📌","pushpin",""],
    ["1246","📍","round pushpin",""],
    ["1247","📎","paperclip",""],
    ["1248","🖇","linked paperclips",""],
    ["1249","📏","straight ruler",""],
    ["1250","📐","triangular ruler",""],
    ["1251","✂","scissors",""],
    ["1252","🗃","card file box",""],
    ["1253","🗄","file cabinet",""],
    ["1254","🗑","wastebasket",""],
    ["1255","🔒","locked",""],
    ["1256","🔓","unlocked",""],
    ["1257","🔏","locked with pen",""],
    ["1258","🔐","locked with key",""],
    ["1259","🔑","key",""],
    ["1260","🗝","old key",""],
    ["1261","🔨","hammer",""],
    ["1262","🪓","axe",""],
    ["1263","⛏","pick",""],
    ["1264","⚒","hammer and pick",""],
    ["1265","🛠","hammer and wrench",""],
    ["1266","🗡","dagger",""],
    ["1267","⚔","crossed swords",""],
    ["1268","🔫","water pistol",""],
    ["1269","🪃","boomerang",""],
    ["1270","🏹","bow and arrow",""],
    ["1271","🛡","shield",""],
    ["1272","🪚","carpentry saw",""],
    ["1273","🔧","wrench",""],
    ["1274","🪛","screwdriver",""],
    ["1275","🔩","nut and bolt",""],
    ["1276","⚙","gear",""],
    ["1277","🗜","clamp",""],
    ["1278","⚖","balance scale",""],
    ["1279","🦯","white cane",""],
    ["1280","🔗","link",""],
    ["1281","⛓","chains",""],
    ["1282","🪝","hook","hook"],
    ["1283","🧰","toolbox","toolbox"],
    ["1284","🧲","magnet","magnet"],
    ["1285","🪜","ladder",""],
    ["1286","⚗","alembic",""],
    ["1287","🧪","test tube",""],
    ["1288","🧫","petri dish",""],
    ["1289","🧬","dna","dna"],
    ["1290","🔬","microscope","microscope"],
    ["1291","🔭","telescope","telescope"],
    ["1292","📡","satellite antenna","antenna"],
    ["1293","💉","syringe","syringe"],
    ["1294","🩸","drop of blood","blood"],
    ["1295","💊","pill",""],
    ["1296","🩹","adhesive bandage",""],
    ["1297","🩺","stethoscope",""],
    ["1298","🚪","door",""],
    ["1299","🛗","elevator",""],
    ["1300","🪞","mirror",""],
    ["1301","🪟","window",""],
    ["1302","🛏","bed",""],
    ["1303","🛋","couch and lamp",""],
    ["1304","🪑","chair",""],
    ["1305","🚽","toilet",""],
    ["1306","🪠","plunger",""],
    ["1307","🚿","shower",""],
    ["1308","🛁","bathtub",""],
    ["1309","🪤","mouse trap",""],
    ["1310","🪒","razor",""],
    ["1311","🧴","lotion bottle",""],
    ["1312","🧷","safety pin",""],
    ["1313","🧹","broom",""],
    ["1314","🧺","basket",""],
    ["1315","🧻","roll of paper",""],
    ["1316","🪣","bucket",""],
    ["1317","🧼","soap",""],
    ["1318","🪥","toothbrush",""],
    ["1319","🧽","sponge",""],
    ["1320","🧯","fire extinguisher",""],
    ["1321","🛒","shopping cart",""],
    ["1322","🚬","cigarette",""],
    ["1323","⚰","coffin",""],
    ["1324","🪦","headstone",""],
    ["1325","⚱","funeral urn",""],
    ["1326","🗿","moai",""],
    ["1327","🪧","placard",""],
    ["1328","🏧","ATM sign",""],
    ["1329","🚮","litter in bin sign",""],
    ["1330","🚰","potable water",""],
    ["1331","♿","wheelchair symbol",""],
    ["1332","🚹","men’s room",""],
    ["1333","🚺","women’s room",""],
    ["1334","🚻","restroom",""],
    ["1335","🚼","baby symbol",""],
    ["1336","🚾","water closet",""],
    ["1337","🛂","passport control",""],
    ["1338","🛃","customs",""],
    ["1339","🛄","baggage claim",""],
    ["1340","🛅","left luggage",""],
    ["1341","⚠","warning",""],
    ["1342","🚸","children crossing",""],
    ["1343","⛔","no entry",""],
    ["1344","🚫","prohibited",""],
    ["1345","🚳","no bicycles",""],
    ["1346","🚭","no smoking",""],
    ["1347","🚯","no littering",""],
    ["1348","🚱","non-potable water",""],
    ["1349","🚷","no pedestrians",""],
    ["1350","📵","no mobile phones",""],
    ["1351","🔞","no one under eighteen",""],
    ["1352","☢","radioactive",""],
    ["1353","☣","biohazard",""],
    ["1354","⬆","up arrow",""],
    ["1355","↗","up-right arrow",""],
    ["1356","➡","right arrow",""],
    ["1357","↘","down-right arrow",""],
    ["1358","⬇","down arrow",""],
    ["1359","↙","down-left arrow",""],
    ["1360","⬅","left arrow",""],
    ["1361","↖","up-left arrow",""],
    ["1362","↕","up-down arrow",""],
    ["1363","↔","left-right arrow",""],
    ["1364","↩","right arrow curving left",""],
    ["1365","↪","left arrow curving right",""],
    ["1366","⤴","right arrow curving up",""],
    ["1367","⤵","right arrow curving down",""],
    ["1368","🔃","clockwise vertical arrows",""],
    ["1369","🔄","counterclockwise arrows button",""],
    ["1370","🔙","BACK arrow",""],
    ["1371","🔚","END arrow",""],
    ["1372","🔛","ON! arrow",""],
    ["1373","🔜","SOON arrow",""],
    ["1374","🔝","TOP arrow",""],
    ["1375","🛐","place of worship",""],
    ["1376","⚛","atom symbol",""],
    ["1377","🕉","om",""],
    ["1378","✡","star of David",""],
    ["1379","☸","wheel of dharma",""],
    ["1380","☯","yin yang",""],
    ["1381","✝","latin cross",""],
    ["1382","☦","orthodox cross",""],
    ["1383","☪","star and crescent",""],
    ["1384","☮","peace symbol",""],
    ["1385","🕎","menorah",""],
    ["1386","🔯","dotted six-pointed star",""],
    ["1387","♈","Aries",""],
    ["1388","♉","Taurus",""],
    ["1389","♊","Gemini",""],
    ["1390","♋","Cancer",""],
    ["1391","♌","Leo",""],
    ["1392","♍","Virgo",""],
    ["1393","♎","Libra",""],
    ["1394","♏","Scorpio",""],
    ["1395","♐","Sagittarius",""],
    ["1396","♑","Capricorn",""],
    ["1397","♒","Aquarius",""],
    ["1398","♓","Pisces",""],
    ["1399","⛎","Ophiuchus",""],
    ["1400","🔀","shuffle tracks button",""],
    ["1401","🔁","repeat button",""],
    ["1402","🔂","repeat single button",""],
    ["1403","▶","play button",""],
    ["1404","⏩","fast-forward button",""],
    ["1405","⏭","next track button",""],
    ["1406","⏯","play or pause button",""],
    ["1407","◀","reverse button",""],
    ["1408","⏪","fast reverse button",""],
    ["1409","⏮","last track button",""],
    ["1410","🔼","upwards button",""],
    ["1411","⏫","fast up button",""],
    ["1412","🔽","downwards button",""],
    ["1413","⏬","fast down button",""],
    ["1414","⏸","pause button",""],
    ["1415","⏹","stop button",""],
    ["1416","⏺","record button",""],
    ["1417","⏏","eject button",""],
    ["1418","🎦","cinema",""],
    ["1419","🔅","dim button",""],
    ["1420","🔆","bright button",""],
    ["1421","📶","antenna bars",""],
    ["1422","📳","vibration mode",""],
    ["1423","📴","mobile phone off",""],
    ["1424","♀","female sign",""],
    ["1425","♂","male sign",""],
    ["1426","⚧","transgender symbol",""],
    ["1427","✖","multiply",""],
    ["1428","➕","plus",""],
    ["1429","➖","minus",""],
    ["1430","➗","divide",""],
    ["1431","♾","infinity",""],
    ["1432","‼","double exclamation mark",""],
    ["1433","⁉","exclamation question mark",""],
    ["1434","❓","red question mark",""],
    ["1435","❔","white question mark",""],
    ["1436","❕","white exclamation mark",""],
    ["1437","❗","red exclamation mark",""],
    ["1438","〰","wavy dash",""],
    ["1439","💱","currency exchange",""],
    ["1440","💲","heavy dollar sign",""],
    ["1441","⚕","medical symbol",""],
    ["1442","♻","recycling symbol",""],
    ["1443","⚜","fleur-de-lis",""],
    ["1444","🔱","trident emblem",""],
    ["1445","📛","name badge",""],
    ["1446","🔰","Japanese symbol for beginner",""],
    ["1447","⭕","hollow red circle",""],
    ["1448","✅","check mark button",""],
    ["1449","☑","check box with check",""],
    ["1450","✔","check mark",""],
    ["1451","❌","cross mark",""],
    ["1452","❎","cross mark button",""],
    ["1453","➰","curly loop",""],
    ["1454","➿","double curly loop",""],
    ["1455","〽","part alternation mark",""],
    ["1456","✳","eight-spoked asterisk",""],
    ["1457","✴","eight-pointed star",""],
    ["1458","❇","sparkle",""],
    ["1459","©","copyright",""],
    ["1460","®","registered",""],
    ["1461","™","trade mark",""],
    ["1462","#️⃣","keycap: #",""],
    ["1463","*️⃣","keycap: *",""],
    ["1464","0️⃣","keycap: 0",""],
    ["1465","1️⃣","keycap: 1",""],
    ["1466","2️⃣","keycap: 2",""],
    ["1467","3️⃣","keycap: 3",""],
    ["1468","4️⃣","keycap: 4",""],
    ["1469","5️⃣","keycap: 5",""],
    ["1470","6️⃣","keycap: 6",""],
    ["1471","7️⃣","keycap: 7",""],
    ["1472","8️⃣","keycap: 8",""],
    ["1473","9️⃣","keycap: 9",""],
    ["1474","🔟","keycap: 10",""],
    ["1475","🔠","input latin uppercase",""],
    ["1476","🔡","input latin lowercase",""],
    ["1477","🔢","input numbers",""],
    ["1478","🔣","input symbols",""],
    ["1479","🔤","input latin letters",""],
    ["1480","🅰","A button (blood type)",""],
    ["1481","🆎","AB button (blood type)",""],
    ["1482","🅱","B button (blood type)",""],
    ["1483","🆑","CL button",""],
    ["1484","🆒","COOL button",""],
    ["1485","🆓","FREE button",""],
    ["1486","ℹ","information",""],
    ["1487","🆔","ID button",""],
    ["1488","Ⓜ","circled M",""],
    ["1489","🆕","NEW button",""],
    ["1490","🆖","NG button",""],
    ["1491","🅾","O button (blood type)",""],
    ["1492","🆗","OK button",""],
    ["1493","🅿","P button",""],
    ["1494","🆘","SOS button",""],
    ["1495","🆙","UP! button",""],
    ["1496","🆚","VS button",""],
    ["1497","🈁","Japanese “here” button",""],
    ["1498","🈂","Japanese “service charge” button",""],
    ["1499","🈷","Japanese “monthly amount” button",""],
    ["1500","🈶","Japanese “not free of charge” button",""],
    ["1501","🈯","Japanese “reserved” button",""],
    ["1502","🉐","Japanese “bargain” button",""],
    ["1503","🈹","Japanese “discount” button",""],
    ["1504","🈚","Japanese “free of charge” button",""],
    ["1505","🈲","Japanese “prohibited” button",""],
    ["1506","🉑","Japanese “acceptable” button",""],
    ["1507","🈸","Japanese “application” button",""],
    ["1508","🈴","Japanese “passing grade” button",""],
    ["1509","🈳","Japanese “vacancy” button",""],
    ["1510","㊗","Japanese “congratulations” button",""],
    ["1511","㊙","Japanese “secret” button",""],
    ["1512","🈺","Japanese “open for business” button",""],
    ["1513","🈵","Japanese “no vacancy” button",""],
    ["1514","🔴","red circle",""],
    ["1515","🟠","orange circle",""],
    ["1516","🟡","yellow circle",""],
    ["1517","🟢","green circle",""],
    ["1518","🔵","blue circle",""],
    ["1519","🟣","purple circle",""],
    ["1520","🟤","brown circle",""],
    ["1521","⚫","black circle",""],
    ["1522","⚪","white circle",""],
    ["1523","🟥","red square",""],
    ["1524","🟧","orange square",""],
    ["1525","🟨","yellow square",""],
    ["1526","🟩","green square",""],
    ["1527","🟦","blue square",""],
    ["1528","🟪","purple square",""],
    ["1529","🟫","brown square",""],
    ["1530","⬛","black large square",""],
    ["1531","⬜","white large square",""],
    ["1532","◼","black medium square",""],
    ["1533","◻","white medium square",""],
    ["1534","◾","black medium-small square",""],
    ["1535","◽","white medium-small square",""],
    ["1536","▪","black small square",""],
    ["1537","▫","white small square",""],
    ["1538","🔶","large orange diamond",""],
    ["1539","🔷","large blue diamond",""],
    ["1540","🔸","small orange diamond",""],
    ["1541","🔹","small blue diamond",""],
    ["1542","🔺","red triangle pointed up",""],
    ["1543","🔻","red triangle pointed down",""],
    ["1544","💠","diamond with a dot",""],
    ["1545","🔘","radio button",""],
    ["1546","🔳","white square button",""],
    ["1547","🔲","black square button",""],
    ["1548","🏁","chequered flag",""],
    ["1549","🚩","triangular flag",""],
    ["1550","🎌","crossed flags",""],
    ["1551","🏴","black flag",""],
    ["1552","🏳","white flag",""],
    ["1553","🏳️‍🌈","rainbow flag",""],
    ["1554","🏳️‍⚧️","transgender flag",""],
    ["1555","🏴‍☠️","pirate flag",""],
    ["1556","🇦🇨","flag: Ascension Island","Ascension Island;Ascensionian"],
    ["1557","🇦🇩","flag: Andorra","Andorra;Andorran"],
    ["1558","🇦🇪","flag: United Arab Emirates","United Arab Emirates;Emirati"],
    ["1559","🇦🇫","flag: Afghanistan","Afghanistan;Afghan"],
    ["1560","🇦🇬","flag: Antigua & Barbuda","Antigua & Barbuda;Antiguan, Barbudan"],
    ["1561","🇦🇮","flag: Anguilla","Anguilla;Anguillan"],
    ["1562","🇦🇱","flag: Albania","Albania;Albanian"],
    ["1563","🇦🇲","flag: Armenia","Armenia;Armenian"],
    ["1564","🇦🇴","flag: Angola","Angola;Angolan"],
    ["1565","🇦🇶","flag: Antarctica","Antarctica;Antarctic"],
    ["1566","🇦🇷","flag: Argentina","Argentina;Argentine"],
    ["1567","🇦🇸","flag: American Samoa","American Samoa;American Samoan"],
    ["1568","🇦🇹","flag: Austria","Austria;Austrian"],
    ["1569","🇦🇺","flag: Australia","Australia;Australian"],
    ["1570","🇦🇼","flag: Aruba","Aruba;Aruban"],
    ["1571","🇦🇽","flag: Åland Islands","Åland Islands;Ålandic"],
    ["1572","🇦🇿","flag: Azerbaijan","Azerbaijan;Azerbaijani"],
    ["1573","🇧🇦","flag: Bosnia & Herzegovina","Bosnia & Herzegovina;Bosnian, Herzegovinian"],
    ["1574","🇧🇧","flag: Barbados","Barbados;Barbadian"],
    ["1575","🇧🇩","flag: Bangladesh","Bangladesh;Bangladeshi"],
    ["1576","🇧🇪","flag: Belgium","Belgium;Belgian"],
    ["1577","🇧🇫","flag: Burkina Faso","Burkina Faso;Burkinabe"],
    ["1578","🇧🇬","flag: Bulgaria","Bulgaria;Bulgarian"],
    ["1579","🇧🇭","flag: Bahrain","Bahrain;Bahraini"],
    ["1580","🇧🇮","flag: Burundi","Burundi;Burundian"],
    ["1581","🇧🇯","flag: Benin","Benin;Beninese"],
    ["1582","🇧🇱","flag: St. Barthélemy","St. Barthélemy;Barthélemois"],
    ["1583","🇧🇲","flag: Bermuda","Bermuda;Bermudian"],
    ["1584","🇧🇳","flag: Brunei","Brunei;Bruneian"],
    ["1585","🇧🇴","flag: Bolivia","Bolivia;Bolivian"],
    ["1586","🇧🇶","flag: Caribbean Netherlands","Caribbean Netherlands;Dutch Caribbean"],
    ["1587","🇧🇷","flag: Brazil","Brazil;Brazilian"],
    ["1588","🇧🇸","flag: Bahamas","Bahamas;Bahamian"],
    ["1589","🇧🇹","flag: Bhutan","Bhutan;Bhutanese"],
    ["1590","🇧🇻","flag: Bouvet Island","Bouvet Island;Bouvet Islander"],
    ["1591","🇧🇼","flag: Botswana","Botswana;Botswanan"],
    ["1592","🇧🇾","flag: Belarus","Belarus;Belarusian"],
    ["1593","🇧🇿","flag: Belize","Belize;Belizean"],
    ["1594","🇨🇦","flag: Canada","Canada;Canadian"],
    ["1595","🇨🇨","flag: Cocos (Keeling) Islands","Cocos (Keeling) Islands;Cocos Islander"],
    ["1596","🇨🇩","flag: Congo - Kinshasa","Congo - Kinshasa;Congolese"],
    ["1597","🇨🇫","flag: Central African Republic","Central African Republic;Central African"],
    ["1598","🇨🇬","flag: Congo - Brazzaville","Congo - Brazzaville;Congolese"],
    ["1599","🇨🇭","flag: Switzerland","Switzerland;Swiss"],
    ["1600","🇨🇮","flag: Côte d’Ivoire","Côte d’Ivoire;Ivorian"],
    ["1601","🇨🇰","flag: Cook Islands","Cook Islands;Cook Islander"],
    ["1602","🇨🇱","flag: Chile","Chile;Chilean"],
    ["1603","🇨🇲","flag: Cameroon","Cameroon;Cameroonian"],
    ["1604","🇨🇳","flag: China","China;Chinese"],
    ["1605","🇨🇴","flag: Colombia","Colombia;Colombian"],
    ["1606","🇨🇵","flag: Clipperton Island","Clipperton Island;Clippertonese"],
    ["1607","🇨🇷","flag: Costa Rica","Costa Rica;Costa Rican"],
    ["1608","🇨🇺","flag: Cuba","Cuba;Cuban"],
    ["1609","🇨🇻","flag: Cape Verde","Cape Verde;Cape Verdean"],
    ["1610","🇨🇼","flag: Curaçao","Curaçao;Curaçaoan"],
    ["1611","🇨🇽","flag: Christmas Island","Christmas Island;Christmas Islander"],
    ["1612","🇨🇾","flag: Cyprus","Cyprus;Cypriot"],
    ["1613","🇨🇿","flag: Czechia","Czechia;Czech"],
    ["1614","🇩🇪","flag: Germany","Germany;German"],
    ["1615","🇩🇬","flag: Diego Garcia","Diego Garcia;Diego Garcia"],
    ["1616","🇩🇯","flag: Djibouti","Djibouti;Djiboutian"],
    ["1617","🇩🇰","flag: Denmark","Denmark;Danish"],
    ["1618","🇩🇲","flag: Dominica","Dominica;Dominican"],
    ["1619","🇩🇴","flag: Dominican Republic","Dominican Republic;Dominican"],
    ["1620","🇩🇿","flag: Algeria","Algeria;Algerian"],
    ["1621","🇪🇦","flag: Ceuta & Melilla","Ceuta & Melilla;Ceutan, Melillan"],
    ["1622","🇪🇨","flag: Ecuador","Ecuador;Ecuadorian"],
    ["1623","🇪🇪","flag: Estonia","Estonia;Estonian"],
    ["1624","🇪🇬","flag: Egypt","Egypt;Egyptian"],
    ["1625","🇪🇭","flag: Western Sahara","Western Sahara;Sahrawi"],
    ["1626","🇪🇷","flag: Eritrea","Eritrea;Eritrean"],
    ["1627","🇪🇸","flag: Spain","Spain;Spanish"],
    ["1628","🇪🇹","flag: Ethiopia","Ethiopia;Ethiopian"],
    ["1629","🇪🇺","flag: European Union","European Union;European"],
    ["1630","🇫🇮","flag: Finland","Finland;Finnish"],
    ["1631","🇫🇯","flag: Fiji","Fiji;Fijian"],
    ["1632","🇫🇰","flag: Falkland Islands","Falkland Islands;Falkland Islander"],
    ["1633","🇫🇲","flag: Micronesia","Micronesia;Micronesian"],
    ["1634","🇫🇴","flag: Faroe Islands","Faroe Islands;Faroese"],
    ["1635","🇫🇷","flag: France","France;French"],
    ["1636","🇬🇦","flag: Gabon","Gabon;Gabonese"],
    ["1637","🇬🇧","flag: United Kingdom","United Kingdom;British"],
    ["1638","🇬🇩","flag: Grenada","Grenada;Grenadian"],
    ["1639","🇬🇪","flag: Georgia","Georgia;Georgian"],
    ["1640","🇬🇫","flag: French Guiana","French Guiana;Guianese"],
    ["1641","🇬🇬","flag: Guernsey","Guernsey;Guernsey"],
    ["1642","🇬🇭","flag: Ghana","Ghana;Ghanaian"],
    ["1643","🇬🇮","flag: Gibraltar","Gibraltar;Gibraltarian"],
    ["1644","🇬🇱","flag: Greenland","Greenland;Greenlandic"],
    ["1645","🇬🇲","flag: Gambia","Gambia;Gambian"],
    ["1646","🇬🇳","flag: Guinea","Guinea;Guinean"],
    ["1647","🇬🇵","flag: Guadeloupe","Guadeloupe;Guadeloupean"],
    ["1648","🇬🇶","flag: Equatorial Guinea","Equatorial Guinea;Equatorial Guinean"],
    ["1649","🇬🇷","flag: Greece","Greece;Greek"],
    ["1650","🇬🇸","flag: South Georgia & South Sandwich Islands","South Georgia & South Sandwich Islands;South Georgian, South Sandwich Islander"],
    ["1651","🇬🇹","flag: Guatemala","Guatemala;Guatemalan"],
    ["1652","🇬🇺","flag: Guam","Guam;Guamanian"],
    ["1653","🇬🇼","flag: Guinea-Bissau","Guinea-Bissau;Bissau-Guinean"],
    ["1654","🇬🇾","flag: Guyana","Guyana;Guyanese"],
    ["1655","🇭🇰","flag: Hong Kong SAR China","Hong Kong SAR China;Hong Konger"],
    ["1656","🇭🇲","flag: Heard & McDonald Islands","Heard & McDonald Islands;Heard and McDonald Islander"],
    ["1657","🇭🇳","flag: Honduras","Honduras;Honduran"],
    ["1658","🇭🇷","flag: Croatia","Croatia;Croatian"],
    ["1659","🇭🇹","flag: Haiti","Haiti;Haitian"],
    ["1660","🇭🇺","flag: Hungary","Hungary;Hungarian"],
    ["1661","🇮🇨","flag: Canary Islands","Canary Islands;Canarian"],
    ["1662","🇮🇩","flag: Indonesia","Indonesia;Indonesian"],
    ["1663","🇮🇪","flag: Ireland","Ireland;Irish"],
    ["1664","🇮🇱","flag: Israel","Israel;Israeli"],
    ["1665","🇮🇲","flag: Isle of Man","Isle of Man;Manx"],
    ["1666","🇮🇳","flag: India","India;Indian"],
    ["1667","🇮🇴","flag: British Indian Ocean Territory","British Indian Ocean Territory;BIOT"],
    ["1668","🇮🇶","flag: Iraq","Iraq;Iraqi"],
    ["1669","🇮🇷","flag: Iran","Iran;Iranian"],
    ["1670","🇮🇸","flag: Iceland","Iceland;Icelandic"],
    ["1671","🇮🇹","flag: Italy","Italy;Italian"],
    ["1672","🇯🇪","flag: Jersey","Jersey;Jersey"],
    ["1673","🇯🇲","flag: Jamaica","Jamaica;Jamaican"],
    ["1674","🇯🇴","flag: Jordan","Jordan;Jordanian"],
    ["1675","🇯🇵","flag: Japan","Japan;Japanese"],
    ["1676","🇰🇪","flag: Kenya","Kenya;Kenyan"],
    ["1677","🇰🇬","flag: Kyrgyzstan","Kyrgyzstan;Kyrgyz"],
    ["1678","🇰🇭","flag: Cambodia","Cambodia;Cambodian"],
    ["1679","🇰🇮","flag: Kiribati","Kiribati;I-Kiribati"],
    ["1680","🇰🇲","flag: Comoros","Comoros;Comorian"],
    ["1681","🇰🇳","flag: St. Kitts & Nevis","St. Kitts & Nevis;Kittitian, Nevisian"],
    ["1682","🇰🇵","flag: North Korea","North Korea;North Korean"],
    ["1683","🇰🇷","flag: South Korea","South Korea;South Korean"],
    ["1684","🇰🇼","flag: Kuwait","Kuwait;Kuwaiti"],
    ["1685","🇰🇾","flag: Cayman Islands","Cayman Islands;Caymanian"],
    ["1686","🇰🇿","flag: Kazakhstan","Kazakhstan;Kazakh"],
    ["1687","🇱🇦","flag: Laos","Laos;Lao"],
    ["1688","🇱🇧","flag: Lebanon","Lebanon;Lebanese"],
    ["1689","🇱🇨","flag: St. Lucia","St. Lucia;Saint Lucian"],
    ["1690","🇱🇮","flag: Liechtenstein","Liechtenstein;Liechtensteiner"],
    ["1691","🇱🇰","flag: Sri Lanka","Sri Lanka;Sri Lankan"],
    ["1692","🇱🇷","flag: Liberia","Liberia;Liberian"],
    ["1693","🇱🇸","flag: Lesotho","Lesotho;Basotho"],
    ["1694","🇱🇹","flag: Lithuania","Lithuania;Lithuanian"],
    ["1695","🇱🇺","flag: Luxembourg","Luxembourg;Luxembourgish"],
    ["1696","🇱🇻","flag: Latvia","Latvia;Latvian"],
    ["1697","🇱🇾","flag: Libya","Libya;Libyan"],
    ["1698","🇲🇦","flag: Morocco","Morocco;Moroccan"],
    ["1699","🇲🇨","flag: Monaco","Monaco;Monacan"],
    ["1700","🇲🇩","flag: Moldova","Moldova;Moldovan"],
    ["1701","🇲🇪","flag: Montenegro","Montenegro;Montenegrin"],
    ["1702","🇲🇫","flag: St. Martin","St. Martin;Saint-Martinoise"],
    ["1703","🇲🇬","flag: Madagascar","Madagascar;Malagasy"],
    ["1704","🇲🇭","flag: Marshall Islands","Marshall Islands;Marshallese"],
    ["1705","🇲🇰","flag: North Macedonia","North Macedonia;Macedonian"],
    ["1706","🇲🇱","flag: Mali","Mali;Malian"],
    ["1707","🇲🇲","flag: Myanmar (Burma)","Myanmar (Burma);Burmese"],
    ["1708","🇲🇳","flag: Mongolia","Mongolia;Mongolian"],
    ["1709","🇲🇴","flag: Macao SAR China","Macao SAR China;Macanese"],
    ["1710","🇲🇵","flag: Northern Mariana Islands","Northern Mariana Islands;Northern Marianan"],
    ["1711","🇲🇶","flag: Martinique","Martinique;Martinican"],
    ["1712","🇲🇷","flag: Mauritania","Mauritania;Mauritanian"],
    ["1713","🇲🇸","flag: Montserrat","Montserrat;Montserratian"],
    ["1714","🇲🇹","flag: Malta","Malta;Maltese"],
    ["1715","🇲🇺","flag: Mauritius","Mauritius;Mauritian"],
    ["1716","🇲🇻","flag: Maldives","Maldives;Maldivian"],
    ["1717","🇲🇼","flag: Malawi","Malawi;Malawian"],
    ["1718","🇲🇽","flag: Mexico","Mexico;Mexican"],
    ["1719","🇲🇾","flag: Malaysia","Malaysia;Malaysian"],
    ["1720","🇲🇿","flag: Mozambique","Mozambique;Mozambican"],
    ["1721","🇳🇦","flag: Namibia","Namibia;Namibian"],
    ["1722","🇳🇨","flag: New Caledonia","New Caledonia;New Caledonian"],
    ["1723","🇳🇪","flag: Niger","Niger;Nigerien"],
    ["1724","🇳🇫","flag: Norfolk Island","Norfolk Island;Norfolk Islander"],
    ["1725","🇳🇬","flag: Nigeria","Nigeria;Nigerian"],
    ["1726","🇳🇮","flag: Nicaragua","Nicaragua;Nicaraguan"],
    ["1727","🇳🇱","flag: Netherlands","Netherlands;Dutch"],
    ["1728","🇳🇴","flag: Norway","Norway;Norwegian"],
    ["1729","🇳🇵","flag: Nepal","Nepal;Nepalese"],
    ["1730","🇳🇷","flag: Nauru","Nauru;Nauruan"],
    ["1731","🇳🇺","flag: Niue","Niue;Niuean"],
    ["1732","🇳🇿","flag: New Zealand","New Zealand;New Zealander"],
    ["1733","🇴🇲","flag: Oman","Oman;Omani"],
    ["1734","🇵🇦","flag: Panama","Panama;Panamanian"],
    ["1735","🇵🇪","flag: Peru","Peru;Peruvian"],
    ["1736","🇵🇫","flag: French Polynesia","French Polynesia;French Polynesian"],
    ["1737","🇵🇬","flag: Papua New Guinea","Papua New Guinea;Papua New Guinean"],
    ["1738","🇵🇭","flag: Philippines","Philippines;Filipino"],
    ["1739","🇵🇰","flag: Pakistan","Pakistan;Pakistani"],
    ["1740","🇵🇱","flag: Poland","Poland;Polish"],
    ["1741","🇵🇲","flag: St. Pierre & Miquelon","St. Pierre & Miquelon;Saint-Pierrais, Miquelonnais"],
    ["1742","🇵🇳","flag: Pitcairn Islands","Pitcairn Islands;Pitcairn Islander"],
    ["1743","🇵🇷","flag: Puerto Rico","Puerto Rico;Puerto Rican"],
    ["1744","🇵🇸","flag: Palestinian Territories","Palestinian Territories;Palestinian"],
    ["1745","🇵🇹","flag: Portugal","Portugal;Portuguese"],
    ["1746","🇵🇼","flag: Palau","Palau;Palauan"],
    ["1747","🇵🇾","flag: Paraguay","Paraguay;Paraguayan"],
    ["1748","🇶🇦","flag: Qatar","Qatar;Qatari"],
    ["1749","🇷🇪","flag: Réunion","Réunion;Réunionese"],
    ["1750","🇷🇴","flag: Romania","Romania;Romanian"],
    ["1751","🇷🇸","flag: Serbia","Serbia;Serbian"],
    ["1752","🇷🇺","flag: Russia","Russia;Russian"],
    ["1753","🇷🇼","flag: Rwanda","Rwanda;Rwandan"],
    ["1754","🇸🇦","flag: Saudi Arabia","Saudi Arabia;Saudi"],
    ["1755","🇸🇧","flag: Solomon Islands","Solomon Islands;Solomon Islander"],
    ["1756","🇸🇨","flag: Seychelles","Seychelles;Seychellois"],
    ["1757","🇸🇩","flag: Sudan","Sudan;Sudanese"],
    ["1758","🇸🇪","flag: Sweden","Sweden;Swedish"],
    ["1759","🇸🇬","flag: Singapore","Singapore;Singaporean"],
    ["1760","🇸🇭","flag: St. Helena","St. Helena;Saint Helenian"],
    ["1761","🇸🇮","flag: Slovenia","Slovenia;Slovenian"],
    ["1762","🇸🇯","flag: Svalbard & Jan Mayen","Svalbard & Jan Mayen;Svalbardian"],
    ["1763","🇸🇰","flag: Slovakia","Slovakia;Slovak"],
    ["1764","🇸🇱","flag: Sierra Leone","Sierra Leone;Sierra Leonean"],
    ["1765","🇸🇲","flag: San Marino","San Marino;Sammarinese"],
    ["1766","🇸🇳","flag: Senegal","Senegal;Senegalese"],
    ["1767","🇸🇴","flag: Somalia","Somalia;Somali"],
    ["1768","🇸🇷","flag: Suriname","Suriname;Surinamese"],
    ["1769","🇸🇸","flag: South Sudan","South Sudan;South Sudanese"],
    ["1770","🇸🇹","flag: São Tomé & Príncipe","São Tomé & Príncipe;São Toméan"],
    ["1771","🇸🇻","flag: El Salvador","El Salvador;Salvadoran"],
    ["1772","🇸🇽","flag: Sint Maarten","Sint Maarten;Sint Maartener"],
    ["1773","🇸🇾","flag: Syria","Syria;Syrian"],
    ["1774","🇸🇿","flag: Eswatini","Eswatini;Swazi"],
    ["1775","🇹🇦","flag: Tristan da Cunha","Tristan da Cunha;Tristanian"],
    ["1776","🇹🇨","flag: Turks & Caicos Islands","Turks & Caicos Islands;Turks and Caicos Islander"],
    ["1777","🇹🇩","flag: Chad","Chad;Chadian"],
    ["1778","🇹🇫","flag: French Southern Territories","French Southern Territories;French Southern Territories"],
    ["1779","🇹🇬","flag: Togo","Togo;Togolese"],
    ["1780","🇹🇭","flag: Thailand","Thailand;Thai"],
    ["1781","🇹🇯","flag: Tajikistan","Tajikistan;Tajik"],
    ["1782","🇹🇰","flag: Tokelau","Tokelau;Tokelauan"],
    ["1783","🇹🇱","flag: Timor-Leste","Timor-Leste;Timorese"],
    ["1784","🇹🇲","flag: Turkmenistan","Turkmenistan;Turkmen"],
    ["1785","🇹🇳","flag: Tunisia","Tunisia;Tunisian"],
    ["1786","🇹🇴","flag: Tonga","Tonga;Tongan"],
    ["1787","🇹🇷","flag: Turkey","Turkey;Turkish"],
    ["1788","🇹🇹","flag: Trinidad & Tobago","Trinidad & Tobago;Trinidadian, Tobagonian"],
    ["1789","🇹🇻","flag: Tuvalu","Tuvalu;Tuvaluan"],
    ["1790","🇹🇼","flag: Taiwan","Taiwan;Taiwanese"],
    ["1791","🇹🇿","flag: Tanzania","Tanzania;Tanzanian"],
    ["1792","🇺🇦","flag: Ukraine","Ukraine;Ukrainian"],
    ["1793","🇺🇬","flag: Uganda","Uganda;Ugandan"],
    ["1794","🇺🇲","flag: U.S. Outlying Islands","U.S. Outlying Islands;U.S. Outlying Islander"],
    ["1795","🇺🇳","flag: United Nations","United Nations;UN"],
    ["1796","🇺🇸","flag: United States","United States;American"],
    ["1797","🇺🇾","flag: Uruguay","Uruguay;Uruguayan"],
    ["1798","🇺🇿","flag: Uzbekistan","Uzbekistan;Uzbek"],
    ["1799","🇻🇦","flag: Vatican City","Vatican City;Vatican"],
    ["1800","🇻🇨","flag: St. Vincent & Grenadines","St. Vincent & Grenadines;Vincentian"],
    ["1801","🇻🇪","flag: Venezuela","Venezuela;Venezuelan"],
    ["1802","🇻🇬","flag: British Virgin Islands","British Virgin Islands;Virgin Islander"],
    ["1803","🇻🇮","flag: U.S. Virgin Islands","U.S. Virgin Islands;Virgin Islander"],
    ["1804","🇻🇳","flag: Vietnam","Vietnam;Vietnamese"],
    ["1805","🇻🇺","flag: Vanuatu","Vanuatu;Ni-Vanuatu"],
    ["1806","🇼🇫","flag: Wallis & Futuna","Wallis & Futuna;Wallisian, Futunan"],
    ["1807","🇼🇸","flag: Samoa","Samoa;Samoan"],
    ["1808","🇽🇰","flag: Kosovo","Kosovo;Kosovar"],
    ["1809","🇾🇪","flag: Yemen","Yemen;Yemeni"],
    ["1810","🇾🇹","flag: Mayotte","Mayotte;Mahoran"],
    ["1811","🇿🇦","flag: South Africa","South Africa;South African"],
    ["1812","🇿🇲","flag: Zambia","Zambia;Zambian"],
    ["1813","🇿🇼","flag: Zimbabwe","Zimbabwe;Zimbabwean"],
    ["1814","🏴󠁧󠁢󠁥󠁮󠁧󠁿","flag: England","England;English"],
    ["1815","🏴󠁧󠁢󠁳󠁣󠁴󠁿","flag: Scotland","Scotland;Scottish"],
    ["1816","🏴󠁧󠁢󠁷󠁬󠁳󠁿","flag: Wales","Wales;Welsh"]
]

flatten_array = [[item[0],item[3].split(";")] for item in array]