name: Build DEV

on:
  workflow_dispatch:

jobs:
  push-image-to-docker-hub:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/arm64/v8]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "S3_KEY_ID=${{ secrets.S3_KEY_ID }}" >> .env
          echo "S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}" >> .env
          echo "S3_HOST=${{ secrets.S3_HOST }}" >> .env
          echo "S3_SECURE=${{ secrets.S3_SECURE }}" >> .env

      - name: Build Docker image
        run: |
          docker build server/ \
            --tag ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.IMAGE_CLEANER_NAME }}:${{ secrets.IMAGE_CLEANER_TAG }} \
            --platform ${{ matrix.platform }} \
            --secret id=.env,src=.env

      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.IMAGE_WORKER_NAME }}:${{ secrets.IMAGE_WORKER_TAG }}
