env:
    WORKER_TAG: newtondotcom/yogocap_worker:latest
    CLEANS3_TAG: newtondotcom/yogocap_cleans3:latest

  on:
    workflow_dispatch:

  jobs:
    workeramd64:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: cd to worker
          run: |
            cd worker
        - name: Build and push AMD64
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: ${{ env.WORKER_TAG }}-amd64
            platforms: linux/amd64
  
    workerarm64:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}        
        - name: cd to worker
          run: |
            cd worker
        - name: Build and push ARM64
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: ${{ env.WORKER_TAG }}-arm64
            platforms: linux/arm64/v8
  
    cleans3amd64:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: cd to worker
          run: |
            cd cleans3
        - name: Build and push AMD64
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: ${{ env.CLEANS3_TAG }}-amd64
            platforms: linux/amd64
  
    cleans3arm64:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}        
        - name: cd to worker
          run: |
            cd cleans3
        - name: Build and push ARM64
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: ${{ env.CLEANS3_TAG }}-arm64
            platforms: linux/arm64/v8
  