---
    name: Image of the worker
    env:
      WORKER_TAG: newtondotcom/yogocap_worker:latest
    on:
      workflow_dispatch:

    jobs:
      worker:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
          - name: Login to Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Build and push AMD64
            uses: docker/build-push-action@v4
            with:
              context: ./worker
              file: ./worker/Dockerfile
              push: true
              tags: ${{ env.WORKER_TAG }}
              platforms: linux/amd64,linux/arm64/v8
    